## 测试算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [6]:
X = iris.data
y = iris.target

In [7]:
X, y

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [8]:
X.shape, y.shape

((150, 4), (150,))

## train test split

In [9]:
# 将数据随机排列
shuffle_indexes = np.random.permutation(len(X))
shuffle_indexes

array([ 90,  19,   4,  72, 120,  33,  49, 111,  94,  47,  13,  35,  43,
       148,  26, 108,  54, 104,  62,  50,  36,  68,   7, 112,  18, 145,
        71,  73, 109,  53,  52,  34,  24,  97, 128, 136,  32,  93,  51,
        61, 103, 138,   0, 100,   3, 149,  25,  74, 134,  76, 139,  21,
       102,  67, 142,  10, 113,  60, 107,  65,  79, 143, 144, 106,  38,
        89,  11,  96,  23, 127,  88,  37,  98, 137,  48, 126, 129, 114,
       110, 132, 131,  12,  66,  91, 101,  29,  99, 124, 141, 105,  41,
        59,  77, 119,  30,  58,   1, 125, 133, 116,   5,  83,  44,  92,
        40,  78, 147, 115, 130,  39,  69,  81,  57, 118, 140,  63,  85,
        55,  95,   2,  17,  28,   6,  14, 122, 123,  31,   9,  87, 135,
        70,  75,  64,  86,  16,  84,  22,  15,  82,  20, 121,   8,  80,
        45,  42, 146,  46,  56, 117,  27])

In [11]:
# 分隔训练数据集和测试数据集
test_ratio = 0.2
test_size = int(len(X)*test_ratio)
test_size

30

In [12]:
test_indexs = shuffle_indexes[:test_size]
train_indexs = shuffle_indexes[test_size:]

X_train = X[train_indexs]
y_train = y[train_indexs]

X_test = X[test_indexs]
y_test = y[test_indexs]

In [13]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((120, 4), (120,), (30, 4), (30,))

## 使用自己的算法

In [16]:
%run ../model_selection.py

In [17]:
X_train, y_train, X_test, y_test = train_test_split(X, y)

In [18]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((120, 4), (120,), (30, 4), (30,))

In [19]:
from KNN import KNNClassifier

In [83]:
knn_clf = KNNClassifier(k=10)
knn_clf.fit(X_train, y_train)
y_predict = knn_clf.predict(X_test)

In [84]:
y_predict

array([1, 1, 2, 2, 1, 0, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 2])

In [85]:
y_test

array([1, 1, 2, 2, 2, 0, 1, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 2])

In [87]:
sum([1 if y_predict[i] == y_test[i] else 0 for i in range(len(y_test))]) / len(y_test)

0.9333333333333333

## 使用sklearn

In [100]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [101]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((120, 4), (120,), (30, 4), (30,))